// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbGScT11cSDLuR8vZCO9hYEw2SyQsmnE',
    appId: '1:124392220684:web:1b9c34167312870422e629',
    messagingSenderId: '124392220684',
    projectId: 'chat-app-fe615',
    authDomain: 'chat-app-fe615.firebaseapp.com',
    storageBucket: 'chat-app-fe615.appspot.com',
    measurementId: 'G-19H13Z4QTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuzfU-9c_zpZHFdXan4JSMNOPYPW4TsU',
    appId: '1:124392220684:android:008b64243e0f931b22e629',
    messagingSenderId: '124392220684',
    projectId: 'chat-app-fe615',
    storageBucket: 'chat-app-fe615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_wxldkpgQgnems4yPglsj31P0LVmqjw',
    appId: '1:124392220684:ios:d2433aa28fbf97a822e629',
    messagingSenderId: '124392220684',
    projectId: 'chat-app-fe615',
    storageBucket: 'chat-app-fe615.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
